---

# Play #1: Create instance in OpenStack.
- hosts: localhost
  gather_facts: false
  tags: 
    - create_instance
  roles:
    - os_create_instance


# Play #2: Generate inventory dynamically with OpenStack instance list.
- hosts: localhost
  gather_facts: false
  tags:
    - generate_inventory
  roles:
    - generate_inventory


# Play #3: Wait for connection with server before gathering facts in next play
- hosts: all
  gather_facts: false
  tasks:
    - name: Wait for connection with server
      wait_for_connection:
        delay: 5
        timeout: 120

        
# Play #4: Install Gitea repository application in the server.
- hosts: all
  gather_facts: true
  become: yes
  become_user: root
  tags:
    - gitea_server
  roles:
    - web_server_ssl
    # - database
    # - repository
    # - backup
