---

- name: Copy nginx repo to /etc/yum.repos.d
  copy: 
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
    # backup: yes

- name: Install nginx package
  yum:
    name: nginx
    state: latest
    update_cache: true

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create document root directory
  file:
    state: directory
    path: /var/www/jmcop.ansible
    owner: root
    group: root
    mode: 0755

- name: Copy index.html into document root directory
  copy: 
    src: index.html
    dest: /var/www/jmcop.ansible
    owner: root
    group: root
    mode: 0644
    # backup: yes

- name: Copy site config
  copy: 
    src: jmcop.ansible.conf
    dest: /etc/nginx/conf.d
    owner: root
    group: root
    mode: 0644
    # backup: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted