---

- name: Create keypair in OpenStack with my public key
  os_keypair:
    state: present
    name: "{{ os_keypair_name }}"
    public_key_file: "{{ role_path }}/files/{{ pub_key_filename}}"

- name: Create instance into OpenStack Asgard
  os_server:
    state: present
    name: "{{ instance_name }}"
    image: "{{ instance_image_id }}"
    key_name: "{{ os_keypair_name }}"
    timeout: 300
    flavor: "{{ instance_flavor }}"
    network: "{{ instance_network_id }}"
    meta:
      hostname: "{{ instance_hostname }}"